### ISSUE TITLE
crash with certain PREFIX situations

### ISSUE THREAD

**Issue by tgpfeiffer** [tialaramex/sparql-query#3]
I'm using sparql-query to issue a federated SPARQL query against a local endpoint. The statement

```
SELECT * WHERE {
  SERVICE <http://dbpedia.org/sparql/>
  {
    SELECT ?res WHERE {
      ?res <http://www.w3.org/2000/01/rdf-schema#label> "Mathematik"@de .
    }
  }
}
```

will return the resource `<http://dbpedia.org/resource/Mathematics>` as intended, while the equivalent query

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT * WHERE {
  SERVICE <http://dbpedia.org/sparql/>
  {
    SELECT ?res WHERE {
      ?res rdfs:label "Mathematik"@de .
    }
  }
}
```

will crash sparql-query:

```
*** glibc detected *** sparql-query/sparql-query: double free or corruption (fasttop): 0x09b97300 ***
======= Backtrace: =========
/lib/tls/i686/cmov/libc.so.6(+0x6b591)[0xb73fb591]
/lib/tls/i686/cmov/libc.so.6(+0x6cde8)[0xb73fcde8]
/lib/tls/i686/cmov/libc.so.6(cfree+0x6d)[0xb73ffecd]
/lib/libglib-2.0.so.0(g_free+0x36)[0xb7702fc6]
sparql-query/sparql-query[0x804bfea]
sparql-query/sparql-query[0x8049e1e]
sparql-query/sparql-query[0x804a8e5]
/lib/tls/i686/cmov/libc.so.6(__libc_start_main+0xe6)[0xb73a6bd6]
sparql-query/sparql-query[0x8049b51]
```

When omitting the PREFIX, sparql-query will display `Missing PREFIXes, adding: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>` and return fine with the expected resource.

The endpoint I'm issuing the query against (which itself stores no triples) is a Joseki server.

**Comment by swh** [comment]
Hi, that's a known problem, and I think it may be fixed in git HEAD, but I'm on holiday for a week or so, and can't check now. 
- Steve

Sent on the move.

**Comment by swh** [comment]
Yes, it's fixed in HEAD.

**Comment by tgpfeiffer** [comment]
Which commit is this change in? In f45c3bd, sparql-query still crashes for me with the above query.

**Comment by swh** [comment]
Sorry, you're right it does still crash with that version, I'll look at it later today.

**Comment by swh** [comment]
OK, I think this is now fixed in 1560408aa63a14342a032e854a0c8c89f642eb2f, can you test?

**Comment by tgpfeiffer** [comment]
Yes, works, thank you!
